--------------------------------------------------------
--  File created - Monday-August-24-2026   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DIM_POPULACAO
--------------------------------------------------------
1TSCPX_SCRIPT_DDL_VERTEX
-- Componentes do grupo:
-- Andreza do Livramento Silva - RM 570964
-- Diego Gaspar - RM 568924
-- João Guilherme Cavalcante Matos - RM 570975
-- Julia de Moraes Barbosa - RM 572997
-- Mariana Ayumi Dantas Kuramitsu - RM 572788
--
-- Comandos DROP TABLE (comentados, apenas para referência de limpeza):
-- DROP TABLE DIM_POPULACAO;
-- DROP TABLE DIM_ESTABELECIMENTO;
-- DROP TABLE DIM_PROFISSIONAL;
-- DROP TABLE FATO_ATENDIMENTOS;

  CREATE TABLE "RM570964"."DIM_POPULACAO" 
   (	"ANO" NUMBER(38,0), 
	"SIGLA_UF" VARCHAR2(26 BYTE), 
	"ID_MUNICIPIO" NUMBER(38,0), 
	"POPULACAO" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
 
--------------------------------------------------------
--  DDL for Table DIM_ESTABELECIMENTO
--------------------------------------------------------

  CREATE TABLE "RM570964"."DIM_ESTABELECIMENTO" 
   (	"ANO" NUMBER(38,0), 
	"MES" NUMBER(38,0), 
	"SIGLA_UF" VARCHAR2(26 BYTE), 
	"ID_MUNICIPIO" NUMBER(38,0), 
	"ID_ESTABELECIMENTO_CNES" VARCHAR2(26 BYTE), 
	"TIPO_UNIDADE" NUMBER(38,0), 
	"ID_NATUREZA_JURIDICA" NUMBER(38,0), 
	"QUANTIDADE_LEITO_CIRURGICO" NUMBER(38,0), 
	"QUANTIDADE_LEITO_CLINICO" NUMBER(38,0), 
	"QUANTIDADE_LEITO_COMPLEMENTAR" NUMBER(38,0), 
	"INDICADOR_ATENCAO_AMBULATORIAL" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table DIM_PROFISSIONAL
--------------------------------------------------------

  CREATE TABLE "RM570964"."DIM_PROFISSIONAL" 
   (	"ANO" NUMBER(38,0), 
	"SIGLA_UF" VARCHAR2(26 BYTE), 
	"ID_MUNICIPIO" NUMBER(38,0), 
	"FAMILIA_OCUPACIONAL_CBO" NUMBER(38,0), 
	"QUANTIDADE_PROFISSIONAIS" NUMBER(38,0), 
	"SOMA_CARGA_HORARIA_AMBULATORIAL" NUMBER(38,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
--------------------------------------------------------
--  DDL for Table FATO_ATENDIMENTOS
--------------------------------------------------------

  CREATE TABLE "RM570964"."FATO_ATENDIMENTOS" 
   (	"ANO" NUMBER(38,0), 
	"MES" NUMBER(38,0), 
	"SIGLA_UF" VARCHAR2(26 BYTE), 
	"ID_MUNICIPIO" NUMBER(38,0), 
	"QUANTIDADE_ATENDIMENTOS" NUMBER(38,0), 
	"VALOR_TOTAL_APROVADO" NUMBER(38,15)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "TBSPC_ALUNOS" ;
